name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  python-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python

    steps:
      - uses: actions/checkout@v4
      
      - name: Install poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: latest

      - name: Poetry install
        run: poetry install

      - name: Run a one-line script
        run: pytest
